### ISSUE TITLE
PROBLEMA -> Fixar aba lateral (missões e progresso)

### ISSUE THREAD

**Issue by ArthurCRodrigues** [ICEI-PUC-Minas-PMGCC-TI/ti-1-pmg-cc-m-20241-g5-descontrole-financeiro#28]
# Fixação da Aba Lateral de Missões e Progresso
## Essa aba precisa estar fixa, ou seja, quando se scrolla pela página, ela deve continuar com sua posição fixa na direita, assim como a barra lateral do **Menu**

![Image](https://github.com/ICEI-PUC-Minas-PMGCC-TI/ti-1-pmg-cc-m-20241-g5-descontrole-financeiro/assets/167308923/372a0380-2911-42c3-886a-61f18e660394)

![Image](https://github.com/ICEI-PUC-Minas-PMGCC-TI/ti-1-pmg-cc-m-20241-g5-descontrole-financeiro/assets/167308923/754ca947-0b00-49ea-bb2c-31e8af640c90)

**Comment by miguelasdp** [comment]
Problema de fixação resolvido
